BEGIN;

CREATE TABLE IF NOT EXISTS subscription_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  customer_type TEXT NOT NULL DEFAULT 'personal',
  monthly_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  yearly_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  description TEXT,
  is_active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tax_years (
  tax_year INTEGER PRIMARY KEY,
  social_security_rate DOUBLE PRECISION NOT NULL DEFAULT 0.062,
  social_security_wage_base DOUBLE PRECISION NOT NULL DEFAULT 168600,
  medicare_rate DOUBLE PRECISION NOT NULL DEFAULT 0.0145,
  additional_medicare_rate DOUBLE PRECISION NOT NULL DEFAULT 0.009,
  additional_medicare_threshold DOUBLE PRECISION NOT NULL DEFAULT 200000,
  mileage_rate DOUBLE PRECISION NOT NULL DEFAULT 0.67,
  capital_gains_rate DOUBLE PRECISION NOT NULL DEFAULT 0.15,
  self_employment_rate DOUBLE PRECISION NOT NULL DEFAULT 0.153,
  child_tax_credit DOUBLE PRECISION NOT NULL DEFAULT 2000,
  default_state_rate DOUBLE PRECISION NOT NULL DEFAULT 0.05,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  first_name TEXT,
  last_name TEXT,
  date_of_birth DATE,
  phone TEXT,
  address_line1 TEXT,
  address_line2 TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  account_type TEXT NOT NULL DEFAULT 'individual',
  customer_type TEXT NOT NULL DEFAULT 'personal',
  business_name TEXT,
  spouse_first_name TEXT,
  spouse_last_name TEXT,
  spouse_date_of_birth DATE,
  filing_status TEXT NOT NULL DEFAULT 'single',
  role TEXT NOT NULL DEFAULT 'user',
  status TEXT NOT NULL DEFAULT 'active',
  plan_id BIGINT REFERENCES subscription_plans(id) ON DELETE SET NULL,
  include_semi_liquid_in_available_cash SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  is_default SMALLINT NOT NULL DEFAULT 0,
  UNIQUE(user_id, name)
);

CREATE TABLE IF NOT EXISTS import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  filename TEXT,
  row_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS investment_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  account_name TEXT NOT NULL,
  account_type TEXT NOT NULL DEFAULT 'brokerage',
  institution TEXT,
  current_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS paychecks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  owner_type TEXT NOT NULL DEFAULT 'self',
  pay_date DATE NOT NULL,
  employer TEXT,
  gross_pay DOUBLE PRECISION NOT NULL DEFAULT 0,
  federal_tax DOUBLE PRECISION NOT NULL DEFAULT 0,
  state_tax DOUBLE PRECISION NOT NULL DEFAULT 0,
  social_security DOUBLE PRECISION NOT NULL DEFAULT 0,
  medicare DOUBLE PRECISION NOT NULL DEFAULT 0,
  benefits_deduction DOUBLE PRECISION NOT NULL DEFAULT 0,
  retirement_contribution DOUBLE PRECISION NOT NULL DEFAULT 0,
  net_pay DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  txn_date DATE NOT NULL,
  description TEXT,
  amount DOUBLE PRECISION NOT NULL,
  payment_method TEXT NOT NULL DEFAULT 'cash',
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  source TEXT NOT NULL DEFAULT 'manual',
  import_batch_id BIGINT,
  cash_account_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bill_name TEXT NOT NULL,
  category TEXT NOT NULL,
  bill_type TEXT NOT NULL DEFAULT 'one_time',
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  due_date DATE NOT NULL,
  recurrence_unit TEXT,
  recurrence_interval_count INTEGER NOT NULL DEFAULT 1,
  recurrence_count INTEGER,
  recurrence_end_type TEXT,
  recurrence_end_date DATE,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bill_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bill_id BIGINT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
  payment_date DATE NOT NULL,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS investments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  investment_account_id BIGINT NOT NULL REFERENCES investment_accounts(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  shares DOUBLE PRECISION NOT NULL,
  purchase_date DATE NOT NULL,
  purchase_price DOUBLE PRECISION NOT NULL,
  sale_date DATE,
  sale_price DOUBLE PRECISION,
  pending_shares SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dividends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  investment_account_id BIGINT NOT NULL REFERENCES investment_accounts(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  pay_date DATE NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  disposition TEXT NOT NULL DEFAULT 'cash',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dependents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  first_name TEXT NOT NULL,
  last_name TEXT,
  date_of_birth DATE,
  relationship TEXT NOT NULL DEFAULT 'child',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tax_deductions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  ded_date DATE NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  miles DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS other_income (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  income_date DATE NOT NULL,
  income_group TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_taxable SMALLINT NOT NULL DEFAULT 1,
  is_self_employment SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS category_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  match_text TEXT NOT NULL,
  category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tax_standard_deductions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tax_year INTEGER NOT NULL REFERENCES tax_years(tax_year) ON DELETE CASCADE,
  filing_status TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  UNIQUE(tax_year, filing_status)
);

CREATE TABLE IF NOT EXISTS tax_brackets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tax_year INTEGER NOT NULL REFERENCES tax_years(tax_year) ON DELETE CASCADE,
  filing_status TEXT NOT NULL,
  seq INTEGER NOT NULL DEFAULT 0,
  upto_income DOUBLE PRECISION,
  rate DOUBLE PRECISION NOT NULL,
  UNIQUE(tax_year, filing_status, seq)
);

CREATE TABLE IF NOT EXISTS tax_state_taxes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tax_year INTEGER NOT NULL REFERENCES tax_years(tax_year) ON DELETE CASCADE,
  state_code TEXT NOT NULL,
  tax_name TEXT NOT NULL,
  tax_type TEXT NOT NULL DEFAULT 'state_income',
  rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  wage_base DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tax_year, state_code, tax_name, tax_type)
);

CREATE TABLE IF NOT EXISTS quarterly_tax_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tax_year INTEGER NOT NULL,
  quarter INTEGER NOT NULL,
  paid_date DATE,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token TEXT UNIQUE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dividend_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  dividend_id BIGINT NOT NULL REFERENCES dividends(id) ON DELETE CASCADE,
  action_type TEXT NOT NULL,
  investment_id BIGINT REFERENCES investments(id) ON DELETE CASCADE,
  other_income_id BIGINT REFERENCES other_income(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS retirement_contribution_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  paycheck_id BIGINT NOT NULL REFERENCES paychecks(id) ON DELETE CASCADE,
  investment_account_id BIGINT NOT NULL REFERENCES investment_accounts(id) ON DELETE CASCADE,
  investment_id BIGINT NOT NULL REFERENCES investments(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cash_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  account_name TEXT NOT NULL,
  account_type TEXT NOT NULL DEFAULT 'checking',
  tier SMALLINT NOT NULL DEFAULT 1,
  institution TEXT,
  is_active SMALLINT NOT NULL DEFAULT 1,
  currency TEXT NOT NULL DEFAULT 'USD',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cash_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  source_type TEXT NOT NULL,
  source_id BIGINT NOT NULL,
  cash_account_id BIGINT NOT NULL REFERENCES cash_accounts(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS account_ledger_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  cash_account_id BIGINT NOT NULL REFERENCES cash_accounts(id) ON DELETE CASCADE,
  entry_date DATE NOT NULL,
  direction TEXT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  category TEXT,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'posted',
  source_type TEXT,
  source_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cash_transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  from_cash_account_id BIGINT NOT NULL REFERENCES cash_accounts(id) ON DELETE CASCADE,
  to_cash_account_id BIGINT NOT NULL REFERENCES cash_accounts(id) ON DELETE CASCADE,
  amount DOUBLE PRECISION NOT NULL,
  transfer_date DATE NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_plan_id ON users(plan_id);
CREATE INDEX IF NOT EXISTS idx_categories_user_id ON categories(user_id);
CREATE INDEX IF NOT EXISTS idx_import_batches_user_id ON import_batches(user_id);
CREATE INDEX IF NOT EXISTS idx_investment_accounts_user_id ON investment_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_paychecks_user_pay_date ON paychecks(user_id, pay_date DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_user_txn_date ON transactions(user_id, txn_date DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_category_id ON transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_bills_user_due_date ON bills(user_id, due_date);
CREATE INDEX IF NOT EXISTS idx_bill_payments_bill_id ON bill_payments(bill_id);
CREATE INDEX IF NOT EXISTS idx_bill_payments_user_payment_date ON bill_payments(user_id, payment_date DESC);
CREATE INDEX IF NOT EXISTS idx_investments_user_account ON investments(user_id, investment_account_id);
CREATE INDEX IF NOT EXISTS idx_dividends_user_pay_date ON dividends(user_id, pay_date DESC);
CREATE INDEX IF NOT EXISTS idx_dependents_user_id ON dependents(user_id);
CREATE INDEX IF NOT EXISTS idx_tax_deductions_user_ded_date ON tax_deductions(user_id, ded_date DESC);
CREATE INDEX IF NOT EXISTS idx_other_income_user_income_date ON other_income(user_id, income_date DESC);
CREATE INDEX IF NOT EXISTS idx_category_rules_user_id ON category_rules(user_id);
CREATE INDEX IF NOT EXISTS idx_quarterly_tax_payments_user_year ON quarterly_tax_payments(user_id, tax_year);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_id ON password_reset_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX IF NOT EXISTS idx_dividend_allocations_dividend_id ON dividend_allocations(dividend_id);
CREATE INDEX IF NOT EXISTS idx_retirement_allocations_paycheck_id ON retirement_contribution_allocations(paycheck_id);
CREATE INDEX IF NOT EXISTS idx_cash_accounts_user_id ON cash_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_cash_allocations_source ON cash_allocations(user_id, source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_account_ledger_entries_account_date ON account_ledger_entries(cash_account_id, entry_date);
CREATE INDEX IF NOT EXISTS idx_account_ledger_entries_source ON account_ledger_entries(user_id, source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_cash_transfers_user_id ON cash_transfers(user_id, transfer_date);
CREATE INDEX IF NOT EXISTS idx_transactions_cash_account_id ON transactions(cash_account_id);

COMMIT;
